name: Creating auto-issue
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
    - uses: actions/checkout@v3
    - name: create an issue
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Simple test issue
        body: my new issue
        assignees: git-madhu,srkambham
